### ISSUE TITLE
packlite option for non-developers

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr-top#2]
Can we also add an option for a packlite?

Before we had this, I had written a bash script that ran git archive on each dependency to extract tarballs.
```
pushd KVTree.git
git archive --format=tar --prefix=kvtree/ -o ../archive/kvtree.tar master
popd
pushd spath.git
git archive --format=tar --prefix=spath/ -o ../archive/spath.tar master
popd
...
```
It doesn't capture the git history, so it's not as useful for SCR developers.  But it generates in a top level tar file that is closer to 5MB instead of 320MB.
```
  5099520 May  7 15:56 archive.tar
320807060 Jun 12 13:21 scr-top-dev.tgz
```
Some code teams want to include this tarball as part their own source repo, so having that smaller file will help.

**Comment by gonsie** [comment]
Sure thing!

I added the `make pack-lite` command, and simplified things a bit (I hope).

Once you’ve run `make clone` you can then do `make dist`, `make pack`, or `make pack-lite`. Each creates an scr-top-xxx.tgz.

After you untar the scr-top-xxx.tgz file, you can run `make unpack` and `make build`.

As an aside, the git-all script is designed to pass a git command to each of the components. It wouldn’t quite work for your use-case since each archive command requires a different prefix argument, but I thought I’d mention it.

**Comment by adammoody** [comment]
Wow, that was fast turn around!  Thanks!

**Comment by gonsie** [comment]
let me know if you want any more features :)
